import { TerminalEntry } from "@/lib/types"

export const experienceLines:TerminalEntry[] = [
    {type: "system", content: {line: "Current role:"}},
    {type: "system", content: {line: "V&V Engineer for Safety I&C Systems on NPP"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Responsibilities:"}},
    {type: "success", content: {key: "-", success: "validation & verification workflows"}},
    {type: "success", content: {key: "-", success: "automated testing"}},
    {type: "success", content: {key: "-", success: "technical documentation"}},
    {type: "success", content: {key: "-", success: "engineering analysis"}},
    {type: "success", content: {key: "-", success: "test preparation and execution"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Automation:"}},
    {type: "success", content: {key: "-", success: "Python scripting"}},
    {type: "success", content: {key: "-", success: "Squish-based UI automation"}},
    {type: "success", content: {key: "-", success: "automated test execution"}},
    {type: "success", content: {key: "-", success: "test script generation"}},
    {type: "success", content: {key: "-", success: "workflow tooling"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Additional tooling:"}},
    {type: "success", content: {key: "-", success: "bulk Excel processing scripts"}},
    {type: "success", content: {key: "-", success: "automation utilities"}},
    {type: "success", content: {key: "-", success: "engineering workflow optimization"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Background:"}},
    {type: "success", content: {key: "-", success: "theoretical physics university background"}},
    {type: "success", content: {key: "-", success: "technical writing"}},
    {type: "success", content: {key: "-", success: "software development projects"}},
    {type: "success", content: {key: "-", success: "frontend-focused development"}},
]