import { TerminalEntry } from "@/lib/types"

export const languagesLines:TerminalEntry[] = [
    {type: "system", content: {line: "Slovak:"}},
    {type: "success", content: {key: "Native speaker", success: ""}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "English:"}},
    {type: "success", content: {key: "-", success: "technical communication"}},
    {type: "success", content: {key: "-", success: "technical documentation"}},
    {type: "success", content: {key: "-", success: "software discussions"}},
    {type: "success", content: {key: "-", success: "university thesis writing"}},
    {type: "success", content: {key: "-", success: "engineering environment communication"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Estimated level:"}},
    {type: "success", content: {key: "B2", success: "(formal classification)"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Practical usage:"}},
    {type: "system", content: {line: "Daily technical and engineering communication."}},
]

export const techStackLines:TerminalEntry[] = [
    {type: "system", content: {line: "Frontend:"}},
    {type: "success", content: {key: "-", success: "React"}},
    {type: "success", content: {key: "-", success: "Next.js"}},
    {type: "success", content: {key: "-", success: "TypeScript"}},
    {type: "success", content: {key: "-", success: "TailwindCSS"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Programming:"}},
    {type: "success", content: {key: "-", success: "JavaScript"}},
    {type: "success", content: {key: "-", success: "TypeScript"}},
    {type: "success", content: {key: "-", success: "Python"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Concepts:"}},
    {type: "success", content: {key: "-", success: "component architecture"}},
    {type: "success", content: {key: "-", success: "state management"}},
    {type: "success", content: {key: "-", success: "async workflows"}},
    {type: "success", content: {key: "-", success: "filesystem modeling"}},
    {type: "success", content: {key: "-", success: "terminal UI systems"}},
    {type: "success", content: {key: "-", success: "responsive layouts"}},
    {type: "success", content: {key: "-", success: "GUI tools automation testing using Squish"}},
    {type: "empty_line", content: {count:1}},
    {type: "system", content: {line: "Tools:"}},
    {type: "success", content: {key: "-", success: "Git"}},
    {type: "success", content: {key: "-", success: "GitHub"}},
    {type: "success", content: {key: "-", success: "VSCode"}},
    {type: "success", content: {key: "-", success: "Linux"}},
    {type: "success", content: {key: "-", success: "npm"}},
    {type: "success", content: {key: "-", success: "Vercel"}},
    {type: "success", content: {key: "-", success: "Squish"}},
]